Module 1 Capstone
GuilhermeGiachellin/Capstone-Project-1 pull request #1
Opened 2021-07-01 18:10 UTC by GuilhermeGiachellin

-The project was maintained in the same format as the template.
-Minor changes were made to accommodate the subject.
-Both versions were developed in this branch.

2021-07-01 20:23 UTC, henatan99 requested changes
Hi @GuilhermeGiachellin , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._
- [x] Your readme should include an acknowledgment that gives appropriate credit to the author of the original design of your project and also any other source you have used. 
- [x] Your readme should include a brief description of the project. The link to the screenshot image is also broken.  
- [x] I haven't seen a video link either in your PR summary or the readme file. Kindly add the video link.  
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-01 20:23 UTC, henatan99 commented on index.html
> +        </nav>
- [x] The navbar (nav element) should have its background transparent or similar to the top section background. For your reference compare the attached screenshots in your and original designs. 

![image](https://user-images.githubusercontent.com/64894927/124180588-13281480-dabd-11eb-9503-e9f1f58fd1d0.png)
![image](https://user-images.githubusercontent.com/64894927/124180589-13281480-dabd-11eb-9536-88d533c6bf05.png)

- [x] The navbar has two sections in the Desktop view in the original design. Please see the attached screenshots for comparison and make the appropriate change. 
![image](https://user-images.githubusercontent.com/64894927/124181224-e7595e80-dabd-11eb-9f2e-17a0bf63f519.png)
![image](https://user-images.githubusercontent.com/64894927/124181317-022bd300-dabe-11eb-9ccc-584a599bc79c.png)

2021-07-01 20:23 UTC, henatan99 commented on index.html
> +    </footer>
- [x] You forgot to add the footer section lower part which shows the logo and copyright text. Please see the attached screenshot for the original design.
![image](https://user-images.githubusercontent.com/64894927/124181846-bd546c00-dabe-11eb-8c6b-c7102b528e94.png)
- You may also need to make some typography changes in the Partners section title.

2021-07-01 20:23 UTC, henatan99 commented on js/dynamic_speakers.js
> +}];
- [x] The speakerInfo array should have 6 objects as in the original design. 
 
![image](https://user-images.githubusercontent.com/64894927/124182716-ea554e80-dabf-11eb-8b04-faab6209bf4c.png)

2021-07-01 20:23 UTC, henatan99 commented on style.css
> +  background: rgba(211, 211, 211, 0.5);
- [ ] You should consider some changes in your styling here as your design has some issues in spacing and contrast compared to the original design. 
![image](https://user-images.githubusercontent.com/64894927/124184555-6c467700-dac2-11eb-8b7c-3c745beafd0d.png)
![image](https://user-images.githubusercontent.com/64894927/124184591-7bc5c000-dac2-11eb-9f27-8274a3edf964.png)

2021-07-01 20:23 UTC, henatan99 commented on style.css
> +  display: flex;
- [ ] You also need to make some changes to the styling here so your design looks very close to the original design. Please see the attached screenshot for reference. 
![image](https://user-images.githubusercontent.com/64894927/124184975-fe4e7f80-dac2-11eb-9121-aee871f63e78.png)
![image](https://user-images.githubusercontent.com/64894927/124185018-10302280-dac3-11eb-9c87-1a7408465dea.png)

2021-07-02 04:06 UTC, smcommits approved these changes
### Status: Approved 👍🏽 

Hi @GuilhermeGiachellin, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-02 04:37 UTC, merged